name: Deploy to VPS

on:
 push:
    branches:
      - main:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy Container to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}${{ secrets.VPS_HOST }} <<'EOF'
          echo 'Deployment started on VPS ...'

          docker stop bnsp-app || true
          docker rm bnsp-app || true

          cd bnsp-si-project
          git pull origin main

          docker build -t bnsp-app .
          docker run -d -p 80:5000 --name bnsp-app bnsp-app

          echo 'Deploment completed.'
          EOF
